config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
   end
  resources :telegrams do
  collection do
  match 'search' => 'telegrams#search', via: [:get, :post], as: :search
  end
end
  match :suglasnost, to: 'telegrams#suglasnost', as: :suglasnost, via: [:post]
  match :suglasnostopca, to: 'telegrams#suglasnostopca', as: :suglasnostopca, via: [:post]
  match :odbijeno, to: 'telegrams#odbijeno', as: :odbijeno, via: [:post]
  match :posaljina, to: 'telegrams#posaljina', as: :posaljina, via: [:post]
  match :printanje, to: 'telegrams#printanje', as: :printanje, via: [:post]
  match :primi, to: 'telegrams#primi', as: :primi, via: [:post]

end

app/models/telegram.rb
class Telegram < ActiveRecord::Base
    before_create :broj
    after_save :stornokorekcija
    after_save :setsuglasnost
    
    
    
    
    def broj
        self.brojBrzojava=Telegram.last.brojBrzojava.to_i+1
        
        if self.salje=="Borka.Kos@hops.hr"
            OdlazniMailer.broj_mailer(self.brojBrzojava, self.vanjskiBroj).deliver_now
        end
        
        if self.prima=="[\"dcpula@ho-pisup.com\"]"
               self.primaNaslov="DC ELEKTROISTRA"
        end
           
            
            
            
    end
    
    def stornokorekcija
      
            if self.storno=="1"
                Telegram.where(brojSuglasnosti: self.brojBrzojava).update_all(storno: "1", stornirao: self.stornirao, stornirano: self.stornirano)
            end
            if self.korigirano!=nil
                Telegram.where(brojSuglasnosti: self.brojBrzojava).update_all(korigirao: self.korigirao, korigirano: self.korigirano)
            end
            if self.odbijeno=="1"
                Telegram.where(brojSuglasnosti: self.brojBrzojava).update_all(odbijeno: "1")
            end
             
        
    end
    
    def setsuglasnost
            if self.suglasnost=="1"
                Telegram.where(brojSuglasnosti: self.brojBrzojava).update_all(suglasnost: "1")
            end
    end
    
    
    
end

app/controllers/telegrams_controller.rb
class TelegramsController < ApplicationController
  before_action :set_telegram, only: [:show, :edit, :update, :destroy]
before_filter :set_search
  # GET /telegrams
  # GET /telegrams.json
  def index
    if params[:q].blank?
      
    @q = Telegram.all.search
    else
   @q = Telegram.ransack(params[:q])
    end
    
    
    @telegrams = @q.result.paginate(page: params[:page], :per_page => 10).order('brojBrzojava DESC')
    ENV['KORISNIK']=current_user.ime+" "+current_user.prezime
    @@tele=@q.result
  end

  # GET /telegrams/1
  # GET /telegrams/1.json
  def show
  end

  # GET /telegrams/new
  def new
    @telegram = Telegram.new
  end

  # GET /telegrams/1/edit
  def edit
  end

  # POST /telegrams
  # POST /telegrams.json
  def create
    @telegram = Telegram.new(telegram_params)

    respond_to do |format|
      if @telegram.save
        format.html { redirect_to @telegram, notice: 'Brzojav uspješno obrađen.' }
        format.json { render :show, status: :created, location: @telegram }
      else
        format.html { render :new }
        format.json { render json: @telegram.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /telegrams/1
  # PATCH/PUT /telegrams/1.json
  def update
    respond_to do |format|
      if @telegram.update(telegram_params)
        format.html { redirect_to telegrams_path, notice: 'Brzojav uspješno obrađen.' }
        format.json { render :show, status: :ok, location: @telegram }
        format.js {}
      else
        format.html { render :edit }
        format.json { render json: @telegram.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /telegrams/1
  # DELETE /telegrams/1.json
  def destroy
    @telegram.destroy
    respond_to do |format|
      format.html { redirect_to telegrams_url, notice: 'Telegram was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def suglasnost
      @telegram_stari = Telegram.find(params[:id])
      ime=current_user.ime
       prezime=current_user.prezime
      Telegram.find(params[:id]).update_attributes(:suglasnost => "1", :brojSuglasnosti => Telegram.last.brojBrzojava.to_i+1)
      ENV['SUGL']=@telegram_stari.brojBrzojava.to_s
      OdlazniMailer.suglasnost_mailer(ime, prezime, Telegram.last.brojBrzojava.to_i+1, @telegram_stari.vanjskiBroj, @telegram_stari.poruka).deliver_now
      flash[:notice] = "Poslana suglasnost."
      
      redirect_to telegrams_path
  end
  
    def suglasnostopca
      @telegram_stari = Telegram.find(params[:id])
       por="SUGLASNI s isklopom"+@telegram_stari.poruka
       ime=current_user.ime
       prezime=current_user.prezime
      Telegram.find(params[:id]).update_attributes(:suglasnost => "1", :brojSuglasnosti => Telegram.last.brojBrzojava.to_i+1)
      ENV['SUGL']=@telegram_stari.brojBrzojava.to_s
      if @telegram_stari.salje.include? "@" 
      OdlazniMailer.opci_mailer(ime, prezime, Telegram.last.brojBrzojava.to_i+1,  @telegram_stari.poruka, @telegram_stari.salje).deliver_now
      else
     Telegram.create!(:brojSuglasnosti => @telegram_stari.brojBrzojava, :salje => ENV['KORISNIK'], :sastavio => ENV['KORISNIK'], :prima => @telegram_stari.salje, :primaNaslov => @telegram_stari.salje, :poruka => por, :suglasnost => "1")
  end
      flash[:notice] = "Poslana suglasnost."
      
      redirect_to telegrams_path
  end
  
  def odbijeno
    @telegram_stari = Telegram.find(params[:id])
   ime=current_user.ime
       prezime=current_user.prezime
 
    Telegram.find(params[:id]).update_attributes(:odbijeno => "1")
    ENV['SUGL']=@telegram_stari.brojBrzojava.to_s
    ENV['RAZLOG']=params[:razlog]
     por="NISMO SUGLASNI "+ENV['RAZLOG']+@telegram_stari.poruka
    if @telegram_stari.salje.include? "@" 
    OdlazniMailer.odbijeno_mailer(ime, prezime, @telegram_stari.salje , Telegram.last.brojBrzojava.to_i+1, @telegram_stari.vanjskiBroj, @telegram_stari.poruka).deliver_now
  else
     Telegram.create!(:brojSuglasnosti => @telegram_stari.brojBrzojava, :salje => ENV['KORISNIK'], :sastavio => ENV['KORISNIK'], :prima => @telegram_stari.salje, :primaNaslov => @telegram_stari.salje, :poruka => por, :odbijeno => "1")
  end
    ENV['RAZLOG']="0"
    flash[:notice] = "Brzojav odbijen."
    redirect_to telegrams_path
  end
  
  def posaljina
      ime=current_user.ime
       prezime=current_user.prezime
    @telegram_stari = Telegram.find(params[:id])
    if params[:telegram].present?
    por=params[:telegram][:poruka]
  else
    por=params[:telegram2][:poruka]
  end
    if params[:ozn]!="n"
    ENV['VEZABR']=@telegram_stari.brojBrzojava.to_s
  else
    ENV['VEZABR']="0"
  end
    if params[:za].include? "@" 
    OdlazniMailer.posaljina_mailer(ime, prezime, Telegram.last.brojBrzojava.to_i+1, por, params[:za]).deliver_now
  else
    if params[:osoba].present?
      osoba=params[:osoba]
    else
      naslov="-"
    end
    Telegram.create!(:salje => ENV['KORISNIK'], :sastavio => ENV['KORISNIK'], :prima => osoba, :primaNaslov => params[:za], :poruka => por, :brojSuglasnosti => ENV['VEZABR'].to_i)
    ENV['VEZABR']="0"
    flash[:notice] = "Brzojav je poslan."
  end
    redirect_to telegrams_path
  end
  
  
  def search
   
  end
  
  def printanje
    
    @telegrams=@@tele
  end
  
  def primi
    por=params[:telegram8][:poruka]
    osoba=params[:osoba]
    organizacija=params[:organizacija]
    Telegram.create!(:prima => ENV['KORISNIK'], :sastavio => organizacija+" - "+osoba, :salje => osoba, :primaNaslov => "MC RIJEKA", :poruka => por)
    flash[:notice] = "Brzojav je primljen."
    redirect_to telegrams_path
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_telegram
      @telegram = Telegram.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def telegram_params
      params.require(:telegram).permit(:primaNaslov, :salje, :prima, :poruka, :brojBrzojava, :vanjskiBroj, :sastavio, :suglasnost, :storno, :stornirano, :stornirao, :brojSuglasnosti, :korigirano, :korigirao)
    end
end

app/helpers/telegrams_helper.rb
module TelegramsHelper
    
    def hrv(dan)
        @dan=dan
        if @dan=="Monday"
                return  @dan="PONEDJELJAK"
            elsif @dan=="Tuesday"
                return  @dan="UTORAK"
            elsif @dan=="Wednesday"
                return  @dan="SRIJEDA"
            elsif @dan=="Thursday"
                return  @dan="ČETVRTAK"
            elsif @dan=="Friday"
                return  @dan="PETAK"
            elsif @dan=="Saturday"
                return  @dan="SUBOTA"
            elsif @dan=="Sunday"
                return  @dan="NEDJELJA"
        end
    end
    
end

app/views/telegrams/_form.html.erb
<%= form_for(@telegram) do |f| %>
  <% if @telegram.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@telegram.errors.count, "error") %> prohibited this telegram from being saved:</h2>

      <ul>
      <% @telegram.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :salje %><br>
    <%= f.text_field :salje %>
  </div>
  <div class="field">
    <%= f.label :prima %><br>
    <%= f.text_field :prima %>
  </div>
  <div class="field">
    
    <%= f.label :poruka %><br>
    <%= f.text_area :poruka, :class => 'ckeditor' %>
  </div>
  <div class="field">
    <%= f.label :brojBrzojava %><br>
    <%= f.text_field :brojBrzojava %>
  </div>
  <div class="field">
    <%= f.label :vanjskiBroj %><br>
    <%= f.text_field :vanjskiBroj %>
  </div>
  <div class="field">
    <%= f.label :sastavio %><br>
    <%= f.text_field :sastavio %>
  </div>
   <div class="field">
    <%= f.label :suglasnost %><br>
    <%= f.text_field :suglasnost %>
  </div>
  <div class="field">
    <%= f.label :storno %><br>
    <%= f.text_field :storno %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/telegrams/_form2.html.erb
<%= form_for(telegram) do |f| %>
<% @telegram=telegram %>
  <% if @telegram.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@telegram.errors.count, "error") %> prohibited this telegram from being saved:</h2>

      <ul>
      <% @telegram.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
  <div class="row">
    <div class="col-lg-12">
    <%= f.label :poruka %><br>
    <%= f.text_area :poruka, :class => 'ckeditor' %>
  </div>
  </div>
   <div class="row">
     <div class="col-lg-12">
    <%= f.label :korigirao %><br>
    <%= f.text_field :korigirao %>
  </div>
  <%= f.hidden_field :korigirano, :value => Time.now %>
   </div>
  <div class="actions">
   <br> <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
  Napravi korekciju
<% end %>
  </div>
<% end %>
</div>

app/views/telegrams/_form3.html.erb
<%= form_for(telegram) do |f| %>
<% @telegram=telegram %>
  <% if @telegram.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@telegram.errors.count, "error") %> prohibited this telegram from being saved:</h2>

      <ul>
      <% @telegram.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
     <div class="row">
     <div class="col-lg-12">
    <%= f.label :stornirao %><br>
    <%= f.text_field :stornirao %>
  </div>
  <%= f.hidden_field :stornirano, :value => Time.now %>
  <%= f.hidden_field :storno, :value => 1 %>
   </div>
  <div class="actions">
   <br> <%= button_tag(type: 'submit', class: "btn btn-warning") do %>
  STORNO
<% end %>
  </div>
<% end %>
</div>

app/views/telegrams/_form4.html.erb
<%= form_for :telegram, url: {action: "odbijeno", params: {id: @telegram.id}} do |f| %>

<div class="container">
     <div class="row">
     <div class="col-lg-12">
    Razlog: 
    <textarea rows="4" cols="50" name="razlog">
zbog</textarea>
  </div>

  

   </div>
   <div class="actions">
   <br> <%= button_tag(type: 'submit', class: "btn btn-warning") do %>
  NISMO SUGLASNI
<% end %>
  </div>

</div>
<% end %>

app/views/telegrams/_form5.html.erb
<%= form_for :telegram, url: {action: "posaljina", params: {id: @telegram.id}} do |f| %>

<div class="container">
     <div class="row">
         
<div class="col-lg-12 ui-front">
 Prima: 
    <input type="text" name="za" id="tbCountries5" />

  </div>
  <div class="col-lg-12">
    <br><%= f.label :poruka %><br>
    <%= f.text_area :poruka, :class => 'ckeditor' %>
  </div>

  

   </div>
   <div class="actions">
   <br> <%= button_tag(type: 'submit', class: "btn btn-warning") do %>
  POŠALJI BRZOJAV
<% end %>

  </div>

</div>
<% end %>

<script>
     $(document).on('ready page:load', function () {
        BindControls();
    });

    function BindControls() {
        var Countriess = ['dcpula@ho-pisup.com', 
            'Borka.Kos@hops.hr', 
            'mczagreb@nesto.nesto'];

        $("#tbCountries5").autocomplete({
            source: Countriess,
            minLength: 0,
            scroll: true
        }).focus(function() {
            $(this).autocomplete("search", "");
        });
    }
    </script>

app/views/telegrams/_form6.html.erb
<%= form_for :telegram, url: {action: "posaljina", params: {id: 164}} do |f| %>

<div class="container">
     <div class="row">
         
<div class="col-lg-12 ui-front">
 Prima: 
    <input type="text" name="za" id="tbCountries6" />

  </div>
  <div class="col-lg-12">
    <br><%= f.label :poruka %><br>
    <%= f.text_area :poruka, :class => 'ckeditor' %>
  </div>

  

   </div>
   <div class="actions">
   <br> <%= button_tag(type: 'submit', class: "btn btn-warning") do %>
  POŠALJI BRZOJAV
<% end %>
<script>
     $(document).on('ready page:load', function () {
        BindControls();
    });

    function BindControls() {
        var Countries = ['dcpula@ho-pisup.com', 
            'Borka.Kos@hops.hr', 
            'mczagreb@nesto.nesto'];

        $('#tbCountries6').autocomplete({
            source: Countries,
            minLength: 0,
            scroll: true
        }).focus(function() {
            $(this).autocomplete("search", "");
        });
    }
    </script>
  </div>

</div>
<% end %>

app/views/telegrams/_form7.html.erb
<%= form_for(telegram) do |f| %>
<% @telegram=telegram %>
  <% if @telegram.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@telegram.errors.count, "error") %> prohibited this telegram from being saved:</h2>

      <ul>
      <% @telegram.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
  <div class="row">
    <div class="col-lg-12">
    <%= f.label :brojSuglasnosti %><br>
    
    <%= f.text_field :brojSuglasnosti %>
  </div>
  </div>
   
  <div class="actions">
   <br> <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
  Poveži brzojav
<% end %>
  </div>
<% end %>
</div>

app/views/telegrams/edit.html.erb
<div id="page-wrapper">

 
            <div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
<h1>Editing Telegram</h1>

<%= render 'form' %>

<%= link_to 'Show', @telegram %> |
<%= link_to 'Back', telegrams_path %>
</div>
</div>
</div>
</div>

app/views/telegrams/new.html.erb
<div id="page-wrapper">

 
            <div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
<h1>New Telegram</h1>

<%= render 'form' %>

<%= link_to 'Back', telegrams_path %>
</div>
</div>
</div>
</div>

app/views/telegrams/printanje.html.erb
<div id="page-wrapper">

 
            <div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
<h4><%= @telegrams.first.created_at.strftime("%d.%m.%Y.") %> - <%= hrv(@telegrams.first.created_at.strftime("%A")) %></h4>
<br><% @telegrams.each do |telegram| %>
<table width="100%" style="page-break-inside: avoid;">
<tbody>
<tr  style="border-left: 2px solid black; border-right: 2px solid black;">
<td style="border-top: 2px solid black;"></td>

<td style="border-left: 1px dashed black; background-color: #C8C8C8 !important; text-align: center; vertical-align: middle; border-top: 2px solid black; padding: 15px; font-size: 18px;" colspan="5"><%= telegram.primaNaslov %></td>

</tr>
<tr  style="border-left: 2px solid black; border-right: 2px solid black;">
<td width="10%"><span style="font-size: 16px;padding-left: 15px; "><strong><%= telegram.brojBrzojava %></strong></span> <% if telegram.vanjskiBroj=="x" or telegram.vanjskiBroj==nil %><% else %> <hr> <span style="font-size: 11px;padding-left: 15px; "><%= telegram.vanjskiBroj %></span><% end %><br><br><%= telegram.created_at.strftime("%d.%m.%Y.") %> <br><%= (telegram.created_at+2.hours).strftime("%k:%M") %></td>
<td style="padding-left: 15px; border-left: 1px dashed black;border-bottom: 1px dashed black;border-top: 1px dashed black;"  colspan="5" rowspan="2"><%= telegram.poruka.html_safe %></td>
</tr>
<tr style="border-left: 2px solid black; border-right: 2px solid black;">
<td>&nbsp;</td>
</tr>
<tr style="border-left: 2px solid black; border-right: 2px solid black;">
<td style="border-bottom: 2px solid black;">&nbsp;</td>
<td style="padding-top: 10px;border-bottom: 2px solid black; border-left: 1px dashed black;padding-left: 15px;" colspan="2">
<p>Poslao: <%= telegram.salje %></p>
<p>Primio: <%= telegram.prima %></p>
</td>
<td style="border-bottom: 2px solid black;">&nbsp;</td>
<td style="border-bottom: 2px solid black; text-align: right; padding-right: 30px;" colspan="2">Sastavio<br><%= telegram.sastavio %></td>
</tr>
<tr><td><br><br></td><td></td><td></td><td></td></tr>
</tbody>
</table>



<% end %>

</div>
</div>
</div>
</div>

app/views/telegrams/search.html.erb
<div class="container">
     <div class="row">
         
<div class="col-lg-12 ui-front">

                         <h3>Pretraži brzojave </h3>
                   
<br>
<%= search_form_for @q do |f| %>
  
  <div class="row">
  <div class="field col-md-3">
    <%= f.label :brojBrzojava, "Barkod" %>
    <%= f.text_field :brojBrzojava_eq, :autofocus => true %>
  </div>
    <div class="field col-md-3">
    <%= f.label :poruka, "Barkod" %>
    <%= f.text_field :poruka_cont %>
  </div>

  </div>
  <br>
  <div class="actions">
    <%=  f.submit  "Traži", class: 'btn btn-success' %>
  </div>
<% end %>
</div>
</div>
</div>

app/views/telegrams/show.html.erb
<div id="page-wrapper">

 
            <div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">

<p id="notice"><%= notice %></p>

<p>
  <strong>Salje:</strong>
  <%= @telegram.salje %>
</p>

<p>
  <strong>Prima:</strong>
  <%= @telegram.prima %>
</p>

<p>
  <strong>Poruka:</strong>
  <%=  @telegram.poruka.html_safe %>
</p>

<p>
  <strong>Brojbrzojava:</strong>
  <%= @telegram.brojBrzojava    %>
</p>

<p>
  <strong>Vanjskibroj:</strong>
  <%= @telegram.vanjskiBroj  %>
</p>

<p>
  <strong>Sastavio:</strong>
  <%= @telegram.sastavio %>
</p>
<p>
  <strong>sugl:</strong>
  <%= @telegram.suglasnost %>
</p>
<% if @telegram.suglasnost=="1" %>
<%= button_to "Suglasnost je izdana ili nije potrebna", {  :controller => "telegrams", :action => "suglasnost",  :id => @telegram.id}, {:disabled => true, class: 'btn btn-success'} %>
<% else %>
<%= button_to "Pošalji suglasnost", {  :controller => "telegrams", :action => "suglasnost",  :id => @telegram.id}, {:disabled => false, class: 'btn btn-success'} %>
<% end %>
<br>
<%= link_to 'Edit', edit_telegram_path(@telegram) %> |
<%= link_to 'Back', telegrams_path %>
</div>
</div>
</div>
</div>

app/views/telegrams/update.js.erb
$(".telegramsTable").replaceWith("<%=j render :partial=> 'telegrams/update', :locals => {telegrams: @telegrams }%>");
$("input[type=text]").val("");
$("modal-window").modal();
$('#myModal').modal('hide');
$('body').removeClass('modal-open');
$('.modal-backdrop').remove();