config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
   end
  resources :telegrams do
  collection do
  match 'search' => 'telegrams#search', via: [:get, :post], as: :search
  end
end
  match :suglasnost, to: 'telegrams#suglasnost', as: :suglasnost, via: [:post]
  match :suglasnostopca, to: 'telegrams#suglasnostopca', as: :suglasnostopca, via: [:post]
  match :odbijeno, to: 'telegrams#odbijeno', as: :odbijeno, via: [:post]
  match :posaljina, to: 'telegrams#posaljina', as: :posaljina, via: [:post]
  match :printanje, to: 'telegrams#printanje', as: :printanje, via: [:post]
  match :primi, to: 'telegrams#primi', as: :primi, via: [:post]

end

app/views/layouts/_footer.html.erb
</div>

app/views/layouts/_header.html.erb
    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href=<%=telegrams_path%>>KNJIGA BRZOJAVA</a>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
                
                
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i><% if current_user.present? %> <%= current_user.ime %> <%= current_user.prezime %><% end%><b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="#"><i class="fa fa-fw fa-user"></i> Profil</a>
                        </li>
                        
                        <li class="divider"></li>
                        <li>
                            <a href=<%=logout_path%>><i class="fa fa-fw fa-power-off"></i> Log Out</a>
                        </li>
                    </ul>
                </li>
            </ul>
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li>
                        <%= link_to  '#', :id => 'mmfm', "data-toggle" => "modal", 'data-target' => '#mmm' do %>
                           <i class="fa fa-fw fa-pencil"></i> Pošalji brzojav
                       <% end %>
                       
                    </li>
                     <li>
                        <%= link_to  '#', :id => 'primilink', "data-toggle" => "modal", 'data-target' => '#primi' do %>
                           <i class="fa fa-fw fa-pencil"></i> Primi brzojav
                       <% end %>
                       
                    </li>
                    <li>
                        <%= link_to  '#', :id => 'mmfsm', "data-toggle" => "modal", 'data-target' => '#sear' do %>
                        <i class="fa fa-fw fa-search"></i> Pretraži brzojave
                       <% end %>
                    </li>
                    <li>
                        <%= link_to  printanje_path, method: :post  do %>
                        <i class="fa fa-fw fa-print"></i> Print
                       <% end %>
                    </li>
                  
                  
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>


    <!-- Custom CSS -->
    <link href="https://brzojav-straho.c9users.io/css/sb-admin.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="https://brzojav-straho.c9users.io/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

  <link href="https://brzojav-straho.c9users.io/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
     <%- if controller_name == 'sessions' %>
 <link href="https://brzojav-straho.c9users.io/css/login.css" rel="stylesheet">
<% end -%>
  <%= csrf_meta_tags %>
  
</head>
<body>
   <%- if controller_name != 'sessions' %>
  <%= render 'layouts/header' %>
<% end -%>
<%= yield %>

<%= render 'layouts/footer' %>
 
</body>
</html>